version: '3.8'

services:
  # Customer Role Service
  customer-role-service:
    image: customer-role-service:latest
    build:
      context: ./customer-role-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/customerdb
#      SPRING_DATASOURCE_USERNAME: customeruser
#      SPRING_DATASOURCE_PASSWORD: customerpass
#    depends_on:
#      - customer-db
#
#  customer-db:
#    image: postgres:15
#    container_name: customer-db
#    environment:
#      POSTGRES_USER: customeruser
#      POSTGRES_PASSWORD: customerpass
#      POSTGRES_DB: customerdb
#    ports:
#      - "5433:5432"

  # Product Catalog Service
  product-catalog-service:
    image: product-catalog-service:latest
    build:
      context: ./product-catalog-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://product-catalog-db:5432/productdb
#      SPRING_DATASOURCE_USERNAME: productuser
#      SPRING_DATASOURCE_PASSWORD: productpass
#    depends_on:
#      - product-catalog-db
#
#  product-catalog-db:
#    image: postgres:15
#    container_name: product-catalog-db
#    environment:
#      POSTGRES_USER: productuser
#      POSTGRES_PASSWORD: productpass
#      POSTGRES_DB: productdb
#    ports:
#      - "5434:5432"

  # Order Management Service
  order-management-service:
    image: order-management-service:latest
    build:
      context: ./order-management-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: orderuser
      SPRING_DATASOURCE_PASSWORD: orderpass
    depends_on:
      - order-db

  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
      POSTGRES_DB: orderdb
    ports:
      - "5435:5432"

  # Payment Service
  payment-service:
    image: payment-service:latest
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: paymentuser
      SPRING_DATASOURCE_PASSWORD: paymentpass
    depends_on:
      - payment-db

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
      POSTGRES_DB: paymentdb
    ports:
      - "5436:5432"