
application:
  name: order-management-service-dev

server:
  port: 8083

productCatalogAdaptor:
  urlTemplate: http://localhost:8082/product/name/{productName}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j2ee_demow09
    username: root
    password: 7400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true