application:
  name: product-catalog-service-dev

server:
  port: 8082

spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j2ee_demow08
    username: root
    password: 7400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
